/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorAñadirCarrera;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Jhony
 */
public class CrudCarrera extends javax.swing.JFrame {

    /**
     * Creates new form CrudCarrera
     */
    
    
  
    public CrudCarrera() {
        initComponents();
        
        
//        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
//        
//                addWindowListener(new WindowAdapter() {
//            @Override
//            public void windowClosing(WindowEvent e) {
//                manejarCierreVentana();
//            }
//        });

    }
    
    private void manejarCierreVentana() {
        // Opciones personalizadas
        String[] opciones = {"Salir", "Continuar"};
        
        // Mostrar cuadro de diálogo de confirmación con opciones personalizadas
        int opcion = JOptionPane.showOptionDialog(
            this,
            "¿Está seguro que desea salir?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[1] // opción predeterminada es "Continuar"
        );

        // Si el usuario selecciona "Salir", cerrar la ventana
        if (opcion == JOptionPane.YES_OPTION) {
            System.out.println("Cerrando FrmNuevaConsulta...");
            dispose();
        }
    }

//    public JButton getBtnAñadirCarrera() {
//        return BtnAñadirCarrera;
//    }
//
//    public void setBtnAñadirCarrera(JButton BtnAñadirCarrera) {
//        this.BtnAñadirCarrera = BtnAñadirCarrera;
//    }
//
//    public JButton getBtnEliminarCarrera() {
//        return BtnEliminarCarrera;
//    }
//
//    public void setBtnEliminarCarrera(JButton BtnEliminarCarrera) {
//        this.BtnEliminarCarrera = BtnEliminarCarrera;
//    }
//
//    public JButton getBtnModificarCarrera() {
//        return BtnModificarCarrera;
//    }
//
//    public void setBtnModificarCarrera(JButton BtnModificarCarrera) {
//        this.BtnModificarCarrera = BtnModificarCarrera;
//    }
//
//    public JTable getTablaCarreras() {
//        return TablaCarreras;
//    }
//
//    public void setTablaCarreras(JTable TablaCarreras) {
//        this.TablaCarreras = TablaCarreras;
//    }
//
//    public JTextField getTxtNuevaCarrera() {
//        return TxtNuevaCarrera;
//    }
//
//    public void setTxtNuevaCarrera(JTextField TxtNuevaCarrera) {
//        this.TxtNuevaCarrera = TxtNuevaCarrera;
//    }
//    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudCarrera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
