/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhony
 */
public class DatosTriage extends javax.swing.JPanel {

    /**
     * Creates new form DatosTriage
     */
    public DatosTriage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaCabeza = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAreaCuello = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtAreaTorax = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtAreaCorazon = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtAreaAbdomen = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtAreaR_Inguinal = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtAreaM_Superior = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtAreaM_Inferior = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        panelRound1 = new Modelo.PanelRound();
        lblSatOxigeno = new javax.swing.JLabel();
        lblEstatura = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        lblFrecRespiratoria = new javax.swing.JLabel();
        lblFreCardiaca = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        txtTemperatura = new javax.swing.JTextField();
        txtEstatura = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtMasaCorporal = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        txtPresionArterial = new javax.swing.JTextField();
        txtFrecRespiratoria = new javax.swing.JTextField();
        txtFreCardiaca = new javax.swing.JTextField();
        txtSaturacion = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        txtLlenadoCapilar = new javax.swing.JTextField();
        txtReaccionPupilar = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        txtGlasgow = new javax.swing.JTextField();
        txtOcular = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        txtMotora = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        txtVerbal = new javax.swing.JTextField();
        TxtTotal = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(64, 172, 159));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cuerpo_1.png"))); // NOI18N
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 170, 370));

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel3.setText("Cabeza");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel4.setText("Cuello");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, 20));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel5.setText("Torax");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, 20));

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel6.setText("Corazon");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 20));

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel7.setText("Abdomen");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 20));

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel8.setText("R_Inguinal");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, 20));

        jLabel9.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel9.setText("M_Inferior");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, 20));

        jLabel10.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel10.setText("M_superior");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, 10));

        txtAreaCabeza.setColumns(20);
        txtAreaCabeza.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        txtAreaCabeza.setLineWrap(true);
        txtAreaCabeza.setRows(5);
        txtAreaCabeza.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtAreaCabeza);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 240, 50));

        jScrollPane6.setRowHeaderView(null);
        jScrollPane6.setViewportView(null);

        txtAreaCuello.setColumns(20);
        txtAreaCuello.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        txtAreaCuello.setLineWrap(true);
        txtAreaCuello.setRows(5);
        txtAreaCuello.setWrapStyleWord(true);
        txtAreaCuello.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        txtAreaCuello.setDragEnabled(true);
        txtAreaCuello.setHighlighter(null);
        txtAreaCuello.setKeymap(null);
        jScrollPane6.setViewportView(txtAreaCuello);

        jPanel8.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 50));

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setToolTipText("");

        txtAreaTorax.setColumns(20);
        txtAreaTorax.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        txtAreaTorax.setLineWrap(true);
        txtAreaTorax.setRows(5);
        txtAreaTorax.setWrapStyleWord(true);
        jScrollPane7.setViewportView(txtAreaTorax);

        jPanel8.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 240, 50));

        txtAreaCorazon.setColumns(20);
        txtAreaCorazon.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        txtAreaCorazon.setLineWrap(true);
        txtAreaCorazon.setRows(5);
        txtAreaCorazon.setWrapStyleWord(true);
        jScrollPane8.setViewportView(txtAreaCorazon);

        jPanel8.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 240, 50));

        txtAreaAbdomen.setColumns(20);
        txtAreaAbdomen.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        txtAreaAbdomen.setLineWrap(true);
        txtAreaAbdomen.setRows(5);
        txtAreaAbdomen.setWrapStyleWord(true);
        jScrollPane9.setViewportView(txtAreaAbdomen);

        jPanel8.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 260, 50));

        txtAreaR_Inguinal.setColumns(20);
        txtAreaR_Inguinal.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        txtAreaR_Inguinal.setLineWrap(true);
        txtAreaR_Inguinal.setRows(5);
        txtAreaR_Inguinal.setWrapStyleWord(true);
        jScrollPane10.setViewportView(txtAreaR_Inguinal);

        jPanel8.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 260, 50));

        txtAreaM_Superior.setColumns(20);
        txtAreaM_Superior.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        txtAreaM_Superior.setLineWrap(true);
        txtAreaM_Superior.setRows(5);
        txtAreaM_Superior.setWrapStyleWord(true);
        jScrollPane11.setViewportView(txtAreaM_Superior);

        jPanel8.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 260, 40));

        txtAreaM_Inferior.setColumns(20);
        txtAreaM_Inferior.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        txtAreaM_Inferior.setLineWrap(true);
        txtAreaM_Inferior.setRows(5);
        txtAreaM_Inferior.setWrapStyleWord(true);
        jScrollPane12.setViewportView(txtAreaM_Inferior);

        jPanel8.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 260, 50));

        jLabel11.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel11.setText("Nivel de prioridad");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No prioritario", "Prioritario", "Emergencia" }));
        jPanel8.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 380, -1));

        jLabel12.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel12.setText("Piel y faneras");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jTextArea9.setLineWrap(true);
        jTextArea9.setRows(5);
        jTextArea9.setWrapStyleWord(true);
        jScrollPane13.setViewportView(jTextArea9);

        jPanel8.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 260, 40));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 560));

        jTabbedPane1.addTab("Examen Fìsico", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOTAS DE PADECIMIENTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Maiandra GD", 1, 12))); // NOI18N
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSatOxigeno.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        lblSatOxigeno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cuidado-de-la-salud.png"))); // NOI18N
        lblSatOxigeno.setText("Saturación de Oxígeno:");
        panelRound1.add(lblSatOxigeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 210, -1));

        lblEstatura.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        lblEstatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Estatura.png"))); // NOI18N
        lblEstatura.setText("Estarura:");
        panelRound1.add(lblEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 210, -1));

        lblPeso.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        lblPeso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Peso.png"))); // NOI18N
        lblPeso.setText("Peso:");
        panelRound1.add(lblPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 210, -1));

        lblTemperatura.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        lblTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/control-de-temperatura.png"))); // NOI18N
        lblTemperatura.setText("Temperatura:");
        panelRound1.add(lblTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 210, -1));

        lblFrecRespiratoria.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        lblFrecRespiratoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Frecuenca respiratoria.png"))); // NOI18N
        lblFrecRespiratoria.setText("Frecuencia Respiratoria:");
        panelRound1.add(lblFrecRespiratoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 210, -1));

        lblFreCardiaca.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        lblFreCardiaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/monitor-de-pulso-cardiaco.png"))); // NOI18N
        lblFreCardiaca.setText("Frecuencia Cardiaca:");
        panelRound1.add(lblFreCardiaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 210, -1));
        panelRound1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 650, 10));

        jLabel15.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/presion-arterial.png"))); // NOI18N
        jLabel15.setText("Presion Arterial:");
        panelRound1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 210, -1));

        jLabel18.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/indice-de-masa-corporal (1).png"))); // NOI18N
        jLabel18.setText("Masa Corporal:");
        panelRound1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 210, -1));

        jLabel55.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/formulario-de-llenado.png"))); // NOI18N
        jLabel55.setText("Llenado Capilar:");
        panelRound1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 210, -1));

        jLabel56.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/totalmente.png"))); // NOI18N
        jLabel56.setText("Total:");
        panelRound1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 210, -1));

        jLabel42.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/discurso.png"))); // NOI18N
        jLabel42.setText("Verbal:");
        panelRound1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 210, -1));

        jLabel41.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/reconocimiento-ocular.png"))); // NOI18N
        jLabel41.setText("Ocular:");
        panelRound1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 210, -1));

        jLabel23.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salud-mental.png"))); // NOI18N
        jLabel23.setText("Glasgow:");
        panelRound1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 210, -1));

        jLabel58.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pupila-del-ojo.png"))); // NOI18N
        jLabel58.setText("Reacción Pupilar:");
        panelRound1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 210, -1));

        jLabel57.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salud.png"))); // NOI18N
        jLabel57.setText("Motora:");
        panelRound1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 210, -1));

        txtTemperatura.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtTemperatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTemperatura.setBorder(null);
        txtTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaActionPerformed(evt);
            }
        });
        panelRound1.add(txtTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 100, 20));

        txtEstatura.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtEstatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstatura.setBorder(null);
        panelRound1.add(txtEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 100, 20));

        txtPeso.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPeso.setBorder(null);
        panelRound1.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 100, 20));

        txtMasaCorporal.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtMasaCorporal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMasaCorporal.setBorder(null);
        panelRound1.add(txtMasaCorporal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 100, 20));
        panelRound1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 270, 10));
        panelRound1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 270, 10));
        panelRound1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 270, 10));
        panelRound1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 270, 10));

        txtPresionArterial.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtPresionArterial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPresionArterial.setBorder(null);
        txtPresionArterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresionArterialActionPerformed(evt);
            }
        });
        panelRound1.add(txtPresionArterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 100, 20));

        txtFrecRespiratoria.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtFrecRespiratoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFrecRespiratoria.setBorder(null);
        panelRound1.add(txtFrecRespiratoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 100, 20));

        txtFreCardiaca.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtFreCardiaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFreCardiaca.setBorder(null);
        panelRound1.add(txtFreCardiaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 100, 20));

        txtSaturacion.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtSaturacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSaturacion.setBorder(null);
        panelRound1.add(txtSaturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 100, 20));
        panelRound1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 270, 10));
        panelRound1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 270, 10));
        panelRound1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 270, 10));
        panelRound1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 270, 10));
        panelRound1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 270, 10));

        txtLlenadoCapilar.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtLlenadoCapilar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLlenadoCapilar.setBorder(null);
        panelRound1.add(txtLlenadoCapilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 100, 20));

        txtReaccionPupilar.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtReaccionPupilar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReaccionPupilar.setBorder(null);
        panelRound1.add(txtReaccionPupilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 100, 20));
        panelRound1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 270, 10));
        panelRound1.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 270, 10));

        txtGlasgow.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtGlasgow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGlasgow.setBorder(null);
        panelRound1.add(txtGlasgow, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 100, 20));

        txtOcular.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtOcular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOcular.setBorder(null);
        txtOcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOcularActionPerformed(evt);
            }
        });
        panelRound1.add(txtOcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 100, 20));
        panelRound1.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 270, 10));

        txtMotora.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtMotora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMotora.setBorder(null);
        panelRound1.add(txtMotora, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 100, 20));
        panelRound1.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 270, 10));
        panelRound1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 270, 10));
        panelRound1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 270, 10));

        txtVerbal.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        txtVerbal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVerbal.setBorder(null);
        panelRound1.add(txtVerbal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 100, 20));

        TxtTotal.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        TxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtTotal.setBorder(null);
        TxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalActionPerformed(evt);
            }
        });
        panelRound1.add(TxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 100, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Padecimiento", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaActionPerformed

    private void txtPresionArterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresionArterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresionArterialActionPerformed

    private void txtOcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOcularActionPerformed

    private void TxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JLabel lblEstatura;
    private javax.swing.JLabel lblFreCardiaca;
    private javax.swing.JLabel lblFrecRespiratoria;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblSatOxigeno;
    private javax.swing.JLabel lblTemperatura;
    private Modelo.PanelRound panelRound1;
    private javax.swing.JTextArea txtAreaAbdomen;
    private javax.swing.JTextArea txtAreaCabeza;
    private javax.swing.JTextArea txtAreaCorazon;
    private javax.swing.JTextArea txtAreaCuello;
    private javax.swing.JTextArea txtAreaM_Inferior;
    private javax.swing.JTextArea txtAreaM_Superior;
    private javax.swing.JTextArea txtAreaR_Inguinal;
    private javax.swing.JTextArea txtAreaTorax;
    private javax.swing.JTextField txtEstatura;
    private javax.swing.JTextField txtFreCardiaca;
    private javax.swing.JTextField txtFrecRespiratoria;
    private javax.swing.JTextField txtGlasgow;
    private javax.swing.JTextField txtLlenadoCapilar;
    private javax.swing.JTextField txtMasaCorporal;
    private javax.swing.JTextField txtMotora;
    private javax.swing.JTextField txtOcular;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPresionArterial;
    private javax.swing.JTextField txtReaccionPupilar;
    private javax.swing.JTextField txtSaturacion;
    private javax.swing.JTextField txtTemperatura;
    private javax.swing.JTextField txtVerbal;
    // End of variables declaration//GEN-END:variables
}
