/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


/**
 *
 * @author Jhony
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    public JButton getBtnIniciarSesion() {
        return BtnIniciarSesion;
    }

    public void setBtnIniciarSesion(JButton BtnIniciarSesion) {
        this.BtnIniciarSesion = BtnIniciarSesion;
    }

    public JPasswordField getPasswordContraseñaLogin() {
        return PasswordContraseñaLogin;
    }

    public void setPasswordContraseñaLogin(JPasswordField PasswordContraseñaLogin) {
        this.PasswordContraseñaLogin = PasswordContraseñaLogin;
    }

    public JTextField getTxtCedulaCorreoLogin() {
        return TxtCedulaCorreoLogin;
    }

    public void setTxtCedulaCorreoLogin(JTextField TxtCedulaCorreoLogin) {
        this.TxtCedulaCorreoLogin = TxtCedulaCorreoLogin;
    }

    public JLabel getTxtLabelRegistrarBtn() {
        return TxtLabelRegistrarBtn;
    }

    public void setTxtLabelRegistrarBtn(JLabel TxtLabelRegistrarBtn) {
        this.TxtLabelRegistrarBtn = TxtLabelRegistrarBtn;
    }
    


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TxtCedulaCorreoLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PasswordContraseñaLogin = new javax.swing.JPasswordField();
        BtnIniciarSesion = new javax.swing.JButton();
        TxtLabelRegistrarBtn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LblLogo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Logo_Instituto.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo Login.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 720));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INICIAR SESIÓN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Maiandra GD", 1, 26))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CONTRASEÑA:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 180, 20));

        TxtCedulaCorreoLogin.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        TxtCedulaCorreoLogin.setToolTipText("Correo o Cédula");
        TxtCedulaCorreoLogin.setBorder(null);
        jPanel2.add(TxtCedulaCorreoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 270, 30));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CORREO:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 160, 20));

        PasswordContraseñaLogin.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        PasswordContraseñaLogin.setToolTipText("Contraseña");
        PasswordContraseñaLogin.setBorder(null);
        jPanel2.add(PasswordContraseñaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 260, 30));

        BtnIniciarSesion.setBackground(new java.awt.Color(64, 172, 159));
        BtnIniciarSesion.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        BtnIniciarSesion.setText("ACEPTAR");
        jPanel2.add(BtnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 140, 30));

        TxtLabelRegistrarBtn.setBackground(new java.awt.Color(255, 255, 255));
        TxtLabelRegistrarBtn.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        TxtLabelRegistrarBtn.setForeground(new java.awt.Color(32, 65, 109));
        TxtLabelRegistrarBtn.setText("Registrate aquí!");
        TxtLabelRegistrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtLabelRegistrarBtnMouseClicked(evt);
            }
        });
        jPanel2.add(TxtLabelRegistrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, -1, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(64, 172, 159));
        jLabel7.setText("¿No tienes Cuenta?");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 310, 10));

        LblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Logo (2).png"))); // NOI18N
        jPanel2.add(LblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 310, 190));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 270, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 270, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 170, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 310, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo_Complemento.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 380, 720));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtLabelRegistrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtLabelRegistrarBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLabelRegistrarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIniciarSesion;
    private javax.swing.JLabel LblLogo;
    private javax.swing.JPasswordField PasswordContraseñaLogin;
    private javax.swing.JTextField TxtCedulaCorreoLogin;
    private javax.swing.JLabel TxtLabelRegistrarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
