/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Joel
 */
public class FrmNuevaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form FrmNuevaConsulta
     */
    public FrmNuevaConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound2 = new Modelo.PanelRound();
        lblPadecimiento = new javax.swing.JLabel();
        btnOpciones = new javax.swing.JButton();
        btnTerminarConsulta = new javax.swing.JButton();
        lblFecha_Actual = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblFecha_Nacimiento = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNumeroCel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelRound1 = new Modelo.PanelRound();
        lblSatOxigeno = new javax.swing.JLabel();
        lblEstatura = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblRefSatOxigeno = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        lblFrecRespiratoria = new javax.swing.JLabel();
        lblFreCardiaca = new javax.swing.JLabel();
        lblRefEstatura = new javax.swing.JLabel();
        lblRefPeso = new javax.swing.JLabel();
        lblRefTemperatura = new javax.swing.JLabel();
        lblRefFrecResp = new javax.swing.JLabel();
        lblRefFreCardiaca = new javax.swing.JLabel();
        txtSaturacion = new javax.swing.JTextField();
        txtEstatura = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtTemperatura = new javax.swing.JTextField();
        txtFrecRespiratoria = new javax.swing.JTextField();
        txtFreCardiaca = new javax.swing.JTextField();
        panelRound3 = new Modelo.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        panelRound5 = new Modelo.PanelRound();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDiagnostico = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaInstrucciones = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaMedicacion = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAreaPlanTrat = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPadecimiento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRound2.add(lblPadecimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 110, 27));

        btnOpciones.setBackground(new java.awt.Color(0, 204, 204));
        btnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesActionPerformed(evt);
            }
        });
        panelRound2.add(btnOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 40, 30));

        btnTerminarConsulta.setBackground(new java.awt.Color(0, 204, 204));
        btnTerminarConsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTerminarConsulta.setText("Terminar Consulta");
        panelRound2.add(btnTerminarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 160, 30));

        lblFecha_Actual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRound2.add(lblFecha_Actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 110, 27));

        lblNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRound2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 27));

        lblFecha_Nacimiento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRound2.add(lblFecha_Nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 27));

        lblEdad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRound2.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 110, 27));

        lblSexo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRound2.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 110, 27));

        lblEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRound2.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 110, 27));

        lblNumeroCel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRound2.add(lblNumeroCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 110, 27));

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 110));

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Historial", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Notas de Padecimiento");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 14, -1, -1));

        panelRound1.setBackground(new java.awt.Color(204, 255, 255));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSatOxigeno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Estatura.png"))); // NOI18N
        lblSatOxigeno.setText("Saturación de Oxígeno:");
        panelRound1.add(lblSatOxigeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lblEstatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Estatura.png"))); // NOI18N
        lblEstatura.setText("Estarura:");
        panelRound1.add(lblEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblPeso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Peso.png"))); // NOI18N
        lblPeso.setText("Peso:");
        panelRound1.add(lblPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblRefSatOxigeno.setText("1.80m");
        panelRound1.add(lblRefSatOxigeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, 20));

        lblTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Estatura.png"))); // NOI18N
        lblTemperatura.setText("Temperatura:");
        panelRound1.add(lblTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblFrecRespiratoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Estatura.png"))); // NOI18N
        lblFrecRespiratoria.setText("Frecuencia Respiratoria:");
        panelRound1.add(lblFrecRespiratoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblFreCardiaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Estatura.png"))); // NOI18N
        lblFreCardiaca.setText("Frecuencia Cardiaca:");
        panelRound1.add(lblFreCardiaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblRefEstatura.setText("1.80m");
        panelRound1.add(lblRefEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, 20));

        lblRefPeso.setText("1.80m");
        panelRound1.add(lblRefPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, 20));

        lblRefTemperatura.setText("1.80m");
        panelRound1.add(lblRefTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, 20));

        lblRefFrecResp.setText("1.80m");
        panelRound1.add(lblRefFrecResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, 20));

        lblRefFreCardiaca.setText("1.80m");
        panelRound1.add(lblRefFreCardiaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, 20));
        panelRound1.add(txtSaturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        txtEstatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstaturaActionPerformed(evt);
            }
        });
        panelRound1.add(txtEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));
        panelRound1.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));
        panelRound1.add(txtTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));
        panelRound1.add(txtFrecRespiratoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));
        panelRound1.add(txtFreCardiaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jPanel3.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 36, 385, 270));

        panelRound3.setBackground(new java.awt.Color(204, 255, 255));
        panelRound3.setRoundBottomLeft(40);
        panelRound3.setRoundBottomRight(40);
        panelRound3.setRoundTopLeft(40);
        panelRound3.setRoundTopRight(40);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Empieza a escribir...\n");
        jScrollPane1.setViewportView(jTextArea1);

        panelRound3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 190));

        jPanel3.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 36, 437, 231));

        jLabel25.setText("Nota de Constulta");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 14, -1, -1));

        jTabbedPane1.addTab("Notas de Padecimiento", jPanel3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound5.setBackground(new java.awt.Color(0, 224, 224));
        panelRound5.setRoundBottomLeft(40);
        panelRound5.setRoundBottomRight(40);
        panelRound5.setRoundTopLeft(40);
        panelRound5.setRoundTopRight(40);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(176, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setText("PLAN DE TRATAMIENTO:");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        txtAreaDiagnostico.setColumns(20);
        txtAreaDiagnostico.setRows(5);
        jScrollPane2.setViewportView(txtAreaDiagnostico);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 600, 50));

        txtAreaInstrucciones.setColumns(20);
        txtAreaInstrucciones.setRows(5);
        jScrollPane3.setViewportView(txtAreaInstrucciones);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 600, 70));

        jLabel27.setText("DIAGNÓSTICO:");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel28.setText("MEDICACIÓN:");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txtAreaMedicacion.setColumns(20);
        txtAreaMedicacion.setRows(5);
        jScrollPane4.setViewportView(txtAreaMedicacion);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 600, 70));

        jLabel29.setText("INSTRUCCIONES MÉDICAS:");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtAreaPlanTrat.setColumns(20);
        txtAreaPlanTrat.setRows(5);
        jScrollPane5.setViewportView(txtAreaPlanTrat);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 320, 130));

        jButton3.setText("Imprimir Receta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, -1, -1));

        panelRound5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 980, 350));

        jPanel6.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1020, 390));

        jLabel6.setText("DIAGNÓSTICO Y TRATAMIENTO");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTabbedPane1.addTab("Diagnóstico y Tratamiento", jPanel6);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1040, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpcionesActionPerformed

    private void txtEstaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstaturaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNuevaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNuevaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNuevaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNuevaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNuevaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnTerminarConsulta;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstatura;
    private javax.swing.JLabel lblFecha_Actual;
    private javax.swing.JLabel lblFecha_Nacimiento;
    private javax.swing.JLabel lblFreCardiaca;
    private javax.swing.JLabel lblFrecRespiratoria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroCel;
    private javax.swing.JLabel lblPadecimiento;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblRefEstatura;
    private javax.swing.JLabel lblRefFreCardiaca;
    private javax.swing.JLabel lblRefFrecResp;
    private javax.swing.JLabel lblRefPeso;
    private javax.swing.JLabel lblRefSatOxigeno;
    private javax.swing.JLabel lblRefTemperatura;
    private javax.swing.JLabel lblSatOxigeno;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTemperatura;
    private Modelo.PanelRound panelRound1;
    private Modelo.PanelRound panelRound2;
    private Modelo.PanelRound panelRound3;
    private Modelo.PanelRound panelRound5;
    private javax.swing.JTextArea txtAreaDiagnostico;
    private javax.swing.JTextArea txtAreaInstrucciones;
    private javax.swing.JTextArea txtAreaMedicacion;
    private javax.swing.JTextArea txtAreaPlanTrat;
    private javax.swing.JTextField txtEstatura;
    private javax.swing.JTextField txtFreCardiaca;
    private javax.swing.JTextField txtFrecRespiratoria;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtSaturacion;
    private javax.swing.JTextField txtTemperatura;
    // End of variables declaration//GEN-END:variables
}
