/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author Jhony
 */
public class FrmRegistrarse extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistrarse
     */
    public FrmRegistrarse() {
        initComponents();
    }
     //GETTERS AND SETTER

    public JButton getBtnRegistrarse() {
        return BtnRegistrarse;
    }

    public void setBtnRegistrarse(JButton BtnRegistrarse) {
        this.BtnRegistrarse = BtnRegistrarse;
    }

    public JPasswordField getJPassContraResg() {
        return JPassContraResg;
    }

    public void setJPassContraResg(JPasswordField JPassContraResg) {
        this.JPassContraResg = JPassContraResg;
    }

    public JPasswordField getJPassNueContraResg() {
        return JPassNueContraResg;
    }

    public void setJPassNueContraResg(JPasswordField JPassNueContraResg) {
        this.JPassNueContraResg = JPassNueContraResg;
    }

    public JTextField getTxtApellidoResg() {
        return TxtApellidoResg;
    }

    public void setTxtApellidoResg(JTextField TxtApellidoResg) {
        this.TxtApellidoResg = TxtApellidoResg;
    }

    public JTextField getTxtCelularResg() {
        return TxtCelularResg;
    }

    public void setTxtCelularResg(JTextField TxtCelularResg) {
        this.TxtCelularResg = TxtCelularResg;
    }

    public JTextField getTxtEmailResg() {
        return TxtEmailResg;
    }

    public void setTxtEmailResg(JTextField TxtEmailResg) {
        this.TxtEmailResg = TxtEmailResg;
    }

    public JTextField getTxtEspecialidadResg() {
        return TxtEspecialidadResg;
    }

    public void setTxtEspecialidadResg(JTextField TxtEspecialidadResg) {
        this.TxtEspecialidadResg = TxtEspecialidadResg;
    }

    public JTextField getTxtIdentiResg() {
        return TxtIdentiResg;
    }

    public void setTxtIdentiResg(JTextField TxtIdentiResg) {
        this.TxtIdentiResg = TxtIdentiResg;
    }

    public JTextField getTxtNombreResg() {
        return TxtNombreResg;
    }

    public void setTxtNombreResg(JTextField TxtNombreResg) {
        this.TxtNombreResg = TxtNombreResg;
    }

    public JTextField getTxtTituloResg() {
        return TxtTituloResg;
    }

    public void setTxtTituloResg(JTextField TxtTituloResg) {
        this.TxtTituloResg = TxtTituloResg;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnRegistrarse = new javax.swing.JButton();
        PanelDatosResg = new javax.swing.JPanel();
        LbEspeciaResg = new javax.swing.JLabel();
        LbCeluResg = new javax.swing.JLabel();
        LbTituloResg = new javax.swing.JLabel();
        LbContraResg = new javax.swing.JLabel();
        LbNomResg = new javax.swing.JLabel();
        LbApelliResg = new javax.swing.JLabel();
        LbEmailResg = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        TxtNombreResg = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        TxtApellidoResg = new javax.swing.JTextField();
        TxtEspecialidadResg = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        TxtCelularResg = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        TxtTituloResg = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        TxtEmailResg = new javax.swing.JTextField();
        JPassContraResg = new javax.swing.JPasswordField();
        LbConfContraResg = new javax.swing.JLabel();
        JPassNueContraResg = new javax.swing.JPasswordField();
        jSeparator12 = new javax.swing.JSeparator();
        PanelIdentifcaResg = new javax.swing.JPanel();
        TxtIdentiResg = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        JLIdentficacionResg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRARSE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Logo_Instituto.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 320, 100));

        BtnRegistrarse.setBackground(new java.awt.Color(64, 172, 159));
        BtnRegistrarse.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        BtnRegistrarse.setText("REGISTRARSE");
        BtnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 190, 30));

        PanelDatosResg.setBackground(new java.awt.Color(255, 255, 255));
        PanelDatosResg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 14))); // NOI18N
        PanelDatosResg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbEspeciaResg.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        LbEspeciaResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbEspeciaResg.setText("Especialidad:");
        PanelDatosResg.add(LbEspeciaResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        LbCeluResg.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        LbCeluResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCeluResg.setText("Celular:");
        PanelDatosResg.add(LbCeluResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 90, -1));

        LbTituloResg.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        LbTituloResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbTituloResg.setText("Titulo:");
        PanelDatosResg.add(LbTituloResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 100, -1));

        LbContraResg.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        LbContraResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbContraResg.setText("Contraseña:");
        PanelDatosResg.add(LbContraResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        LbNomResg.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        LbNomResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbNomResg.setText("Nombres:");
        PanelDatosResg.add(LbNomResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 110, -1));

        LbApelliResg.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        LbApelliResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbApelliResg.setText("Apellidos:");
        PanelDatosResg.add(LbApelliResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 100, -1));

        LbEmailResg.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        LbEmailResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbEmailResg.setText("Email:");
        PanelDatosResg.add(LbEmailResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 110, -1));
        PanelDatosResg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 200, 10));

        TxtNombreResg.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        TxtNombreResg.setBorder(null);
        PanelDatosResg.add(TxtNombreResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, 20));
        PanelDatosResg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 200, 10));

        TxtApellidoResg.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        TxtApellidoResg.setBorder(null);
        PanelDatosResg.add(TxtApellidoResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 200, 20));

        TxtEspecialidadResg.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        TxtEspecialidadResg.setBorder(null);
        PanelDatosResg.add(TxtEspecialidadResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 200, 20));
        PanelDatosResg.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 200, 10));
        PanelDatosResg.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 200, 10));

        TxtCelularResg.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        TxtCelularResg.setBorder(null);
        PanelDatosResg.add(TxtCelularResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 200, 20));
        PanelDatosResg.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 200, 10));

        TxtTituloResg.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        TxtTituloResg.setBorder(null);
        PanelDatosResg.add(TxtTituloResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 200, 20));
        PanelDatosResg.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 200, 10));
        PanelDatosResg.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 200, 10));

        TxtEmailResg.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        TxtEmailResg.setBorder(null);
        PanelDatosResg.add(TxtEmailResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 200, 20));

        JPassContraResg.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        JPassContraResg.setBorder(null);
        PanelDatosResg.add(JPassContraResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 200, 20));

        LbConfContraResg.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        LbConfContraResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbConfContraResg.setText("Confirmar Contraseña:");
        PanelDatosResg.add(LbConfContraResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        JPassNueContraResg.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        JPassNueContraResg.setBorder(null);
        PanelDatosResg.add(JPassNueContraResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 200, 20));
        PanelDatosResg.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 200, 10));

        PanelIdentifcaResg.setBackground(new java.awt.Color(255, 255, 255));
        PanelIdentifcaResg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identificación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 14))); // NOI18N
        PanelIdentifcaResg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtIdentiResg.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        TxtIdentiResg.setBorder(null);
        PanelIdentifcaResg.add(TxtIdentiResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 280, 20));
        PanelIdentifcaResg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 280, 10));

        JLIdentficacionResg.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        JLIdentficacionResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLIdentficacionResg.setText("Cedula:");
        PanelIdentifcaResg.add(JLIdentficacionResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        PanelDatosResg.add(PanelIdentifcaResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 400, 60));

        jPanel1.add(PanelDatosResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 960, 400));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 1020, 580));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo Login Medida Exacta.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrarse;
    public javax.swing.JLabel JLIdentficacionResg;
    private javax.swing.JPasswordField JPassContraResg;
    private javax.swing.JPasswordField JPassNueContraResg;
    public javax.swing.JLabel LbApelliResg;
    public javax.swing.JLabel LbCeluResg;
    public javax.swing.JLabel LbConfContraResg;
    public javax.swing.JLabel LbContraResg;
    public javax.swing.JLabel LbEmailResg;
    public javax.swing.JLabel LbEspeciaResg;
    public javax.swing.JLabel LbNomResg;
    public javax.swing.JLabel LbTituloResg;
    private javax.swing.JPanel PanelDatosResg;
    private javax.swing.JPanel PanelIdentifcaResg;
    public javax.swing.JTextField TxtApellidoResg;
    public javax.swing.JTextField TxtCelularResg;
    public javax.swing.JTextField TxtEmailResg;
    public javax.swing.JTextField TxtEspecialidadResg;
    public javax.swing.JTextField TxtIdentiResg;
    public javax.swing.JTextField TxtNombreResg;
    public javax.swing.JTextField TxtTituloResg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
