/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author mauca
 */
public class PanelDatosHISTORIAL extends javax.swing.JPanel {

    /**
     * Creates new form PanelReportes
     */
    public PanelDatosHISTORIAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNLReporte = new javax.swing.JPanel();
        PNLIdentifiReport = new javax.swing.JPanel();
        JLbCedulaIngreRepor = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        TxtCedBuscarReport = new javax.swing.JTextField();
        BtnBuscarReport = new javax.swing.JButton();
        PNLDatosReport = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLDatReport = new javax.swing.JTable();
        PNLSeleccionReport = new javax.swing.JPanel();
        CBXSeleccReport = new javax.swing.JComboBox<>();
        BtnSeleccionarReport = new javax.swing.JButton();
        PNLReportGrafico = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 680));
        setMinimumSize(new java.awt.Dimension(1280, 680));
        setPreferredSize(new java.awt.Dimension(1280, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PNLReporte.setBackground(new java.awt.Color(255, 255, 255));
        PNLReporte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPORTE HISTORIAL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Maiandra GD", 1, 48))); // NOI18N
        PNLReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PNLIdentifiReport.setBackground(new java.awt.Color(255, 255, 255));
        PNLIdentifiReport.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IDENTIFICACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 14))); // NOI18N
        PNLIdentifiReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLbCedulaIngreRepor.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 16)); // NOI18N
        JLbCedulaIngreRepor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLbCedulaIngreRepor.setText("Ingrese la cédula:");
        PNLIdentifiReport.add(JLbCedulaIngreRepor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, -1));
        PNLIdentifiReport.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 320, 10));

        TxtCedBuscarReport.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        TxtCedBuscarReport.setBorder(null);
        PNLIdentifiReport.add(TxtCedBuscarReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 320, 20));

        BtnBuscarReport.setBackground(new java.awt.Color(64, 172, 159));
        BtnBuscarReport.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        BtnBuscarReport.setText("BUSCAR");
        BtnBuscarReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarReportActionPerformed(evt);
            }
        });
        PNLIdentifiReport.add(BtnBuscarReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 110, -1));

        PNLReporte.add(PNLIdentifiReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 680, 90));

        PNLDatosReport.setBackground(new java.awt.Color(255, 255, 255));
        PNLDatosReport.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS GENERALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 18))); // NOI18N
        PNLDatosReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TBLDatReport.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        TBLDatReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Edad", "Carrera"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TBLDatReport);

        PNLDatosReport.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 640, 350));

        PNLReporte.add(PNLDatosReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 680, 400));

        PNLSeleccionReport.setBackground(new java.awt.Color(255, 255, 255));
        PNLSeleccionReport.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECCIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 15))); // NOI18N
        PNLSeleccionReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CBXSeleccReport.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        CBXSeleccReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Año" }));
        CBXSeleccReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBXSeleccReportActionPerformed(evt);
            }
        });
        PNLSeleccionReport.add(CBXSeleccReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, 30));

        BtnSeleccionarReport.setBackground(new java.awt.Color(64, 172, 159));
        BtnSeleccionarReport.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        BtnSeleccionarReport.setText("SELECCIONAR");
        BtnSeleccionarReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionarReportActionPerformed(evt);
            }
        });
        PNLSeleccionReport.add(BtnSeleccionarReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 130, 30));

        PNLReporte.add(PNLSeleccionReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 450, 90));

        PNLReportGrafico.setBackground(new java.awt.Color(255, 255, 255));
        PNLReportGrafico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPORTE GRAFICO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 18))); // NOI18N

        javax.swing.GroupLayout PNLReportGraficoLayout = new javax.swing.GroupLayout(PNLReportGrafico);
        PNLReportGrafico.setLayout(PNLReportGraficoLayout);
        PNLReportGraficoLayout.setHorizontalGroup(
            PNLReportGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        PNLReportGraficoLayout.setVerticalGroup(
            PNLReportGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        PNLReporte.add(PNLReportGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 450, 400));

        add(PNLReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 1200, 620));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo Login.png"))); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 1960, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarReportActionPerformed

    private void BtnSeleccionarReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionarReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSeleccionarReportActionPerformed

    private void CBXSeleccReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBXSeleccReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBXSeleccReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarReport;
    private javax.swing.JButton BtnSeleccionarReport;
    private javax.swing.JComboBox<String> CBXSeleccReport;
    private javax.swing.JLabel Fondo;
    public javax.swing.JLabel JLbCedulaIngreRepor;
    private javax.swing.JPanel PNLDatosReport;
    private javax.swing.JPanel PNLIdentifiReport;
    private javax.swing.JPanel PNLReportGrafico;
    private javax.swing.JPanel PNLReporte;
    private javax.swing.JPanel PNLSeleccionReport;
    private javax.swing.JTable TBLDatReport;
    public javax.swing.JTextField TxtCedBuscarReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
