/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorPerfilDoctor;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class PerfilDoctor extends javax.swing.JPanel {

    ControladorPerfilDoctor control;
    public PerfilDoctor() {
        initComponents();
        control = new ControladorPerfilDoctor(this);
    }
    
     
    public JButton getBtneditar() {
        return Btneditar;
    }

    public void setBtneditar(JButton BtnRegistrarse) {
        this.Btneditar = BtnRegistrarse;
    }
    public JButton getbtncontra() {
        return btncontra;
    }

    public void setbtncontra(JButton BtnRegistrarse) {
        this.btncontra = BtnRegistrarse;
    }

    

    public JTextField getTxtApellidoResg() {
        return TxtApellidoResg;
    }

    public void setTxtApellidoResg(JTextField TxtApellidoResg) {
        this.TxtApellidoResg = TxtApellidoResg;
    }

    public JTextField getTxtCelularResg() {
        return TxtCelularResg;
    }

    public void setTxtCelularResg(JTextField TxtCelularResg) {
        this.TxtCelularResg = TxtCelularResg;
    }

    public JTextField getTxtEmailResg() {
        return TxtEmailResg;
    }

    public void setTxtEmailResg(JTextField TxtEmailResg) {
        this.TxtEmailResg = TxtEmailResg;
    }

    public JTextField getTxtEspecialidadResg() {
        return TxtEspecialidadResg;
    }

    public void setTxtEspecialidadResg(JTextField TxtEspecialidadResg) {
        this.TxtEspecialidadResg = TxtEspecialidadResg;
    }

    public JTextField getTxtIdentiResg() {
        return TxtIdentiResg;
    }

    public void setTxtIdentiResg(JTextField TxtIdentiResg) {
        this.TxtIdentiResg = TxtIdentiResg;
    }

    public JTextField getTxtNombreResg() {
        return TxtNombreResg;
    }

    public void setTxtNombreResg(JTextField TxtNombreResg) {
        this.TxtNombreResg = TxtNombreResg;
    }

    public JTextField getTxtTituloResg() {
        return TxtTituloResg;
    }

    public void setTxtTituloResg(JTextField TxtTituloResg) {
        this.TxtTituloResg = TxtTituloResg;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btneditar = new javax.swing.JButton();
        TxtIdentiResg = new javax.swing.JTextField();
        JLIdentficacionResg = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        LbNomResg = new javax.swing.JLabel();
        TxtNombreResg = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        LbEspeciaResg = new javax.swing.JLabel();
        LbEmailResg = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        TxtEmailResg = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        TxtEspecialidadResg = new javax.swing.JTextField();
        TxtApellidoResg = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        TxtCelularResg = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        TxtTituloResg = new javax.swing.JTextField();
        LbTituloResg = new javax.swing.JLabel();
        LbCeluResg = new javax.swing.JLabel();
        LbApelliResg = new javax.swing.JLabel();
        btncontra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERFIL DOCTOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 1, 18))); // NOI18N
        setMaximumSize(new java.awt.Dimension(1280, 680));
        setMinimumSize(new java.awt.Dimension(1280, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btneditar.setBackground(new java.awt.Color(0, 153, 153));
        Btneditar.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-editar.png"))); // NOI18N
        Btneditar.setText("EDITAR PERFIL");
        Btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtneditarActionPerformed(evt);
            }
        });
        add(Btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 230, 30));

        TxtIdentiResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        TxtIdentiResg.setBorder(null);
        TxtIdentiResg.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        add(TxtIdentiResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 200, 20));

        JLIdentficacionResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        JLIdentficacionResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLIdentficacionResg.setText("Cédula:");
        add(JLIdentficacionResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, 20));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 200, 20));

        LbNomResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        LbNomResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbNomResg.setText("Nombre:");
        add(LbNomResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 110, -1));

        TxtNombreResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        TxtNombreResg.setBorder(null);
        add(TxtNombreResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 200, 20));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 200, 10));

        LbEspeciaResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        LbEspeciaResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbEspeciaResg.setText("Especialidad:");
        add(LbEspeciaResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));

        LbEmailResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        LbEmailResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbEmailResg.setText("E-mail:");
        add(LbEmailResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 110, -1));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, 200, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 200, 10));

        TxtEmailResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        TxtEmailResg.setBorder(null);
        add(TxtEmailResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 200, 20));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 200, 10));

        TxtEspecialidadResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        TxtEspecialidadResg.setBorder(null);
        add(TxtEspecialidadResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 200, 20));

        TxtApellidoResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        TxtApellidoResg.setBorder(null);
        add(TxtApellidoResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 200, 20));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 200, 10));

        TxtCelularResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        TxtCelularResg.setBorder(null);
        add(TxtCelularResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 630, 200, 20));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 650, 200, 10));

        TxtTituloResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        TxtTituloResg.setBorder(null);
        add(TxtTituloResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 560, 200, 20));

        LbTituloResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        LbTituloResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbTituloResg.setText("Título:");
        add(LbTituloResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 90, -1));

        LbCeluResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        LbCeluResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCeluResg.setText("Celular:");
        add(LbCeluResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, 90, -1));

        LbApelliResg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        LbApelliResg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbApelliResg.setText("Apellido:");
        add(LbApelliResg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 100, -1));

        btncontra.setBackground(new java.awt.Color(30, 53, 99));
        btncontra.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        btncontra.setForeground(new java.awt.Color(255, 255, 255));
        btncontra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-editar.png"))); // NOI18N
        btncontra.setText("EDITAR CONTRASEÑA");
        add(btncontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/marco2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, 270));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/marco1.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/doctca.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, -1, 750));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/perfil1.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 200, 200));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/marco3.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtneditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtneditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btneditar;
    public javax.swing.JLabel JLIdentficacionResg;
    public javax.swing.JLabel LbApelliResg;
    public javax.swing.JLabel LbCeluResg;
    public javax.swing.JLabel LbEmailResg;
    public javax.swing.JLabel LbEspeciaResg;
    public javax.swing.JLabel LbNomResg;
    public javax.swing.JLabel LbTituloResg;
    public javax.swing.JTextField TxtApellidoResg;
    public javax.swing.JTextField TxtCelularResg;
    public javax.swing.JTextField TxtEmailResg;
    public javax.swing.JTextField TxtEspecialidadResg;
    public javax.swing.JTextField TxtIdentiResg;
    public javax.swing.JTextField TxtNombreResg;
    public javax.swing.JTextField TxtTituloResg;
    private javax.swing.JButton btncontra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables

   
}
